[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run deploy"
healthcheckPath = "/health"
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"